### ISSUE TITLE
Support latest librdkafka versions

### ISSUE THREAD

**Issue by mren** [sutoiku/node-kafka#2]
Hello @psq and @hmalphettes 

I hope you're fine. I just created with my colleague @gesundkrank  a patch for your bindings to support the latest version of librdkafka.
The patch was relativly simple. You can have a look at it here 088266fd585c7054fcab201eb676ea37058c05e9

My question now is. Are you interested in updating the library?

**Comment by psq** [comment]
we haven't been actively using node-kafka lately.  That said, @mren, we'd be happy to merge a pull request.

Does the patch includes support for the latest V8 version (from node 0.12 and latest io.js)?

Also, I'd be happy to add you as a committer.

**Comment by mren** [comment]
Hey @psq,
thanks for the feedback.
I will create a pull request for you.

> Does the patch includes support for the latest V8 version (from node 0.12 and latest io.js)?
Currently the library only compiles with node 0.10. We investigated [nan](https://github.com/nodejs/nan) as an abstraction layer for native libraries to make it compatible with different node versions. Perhaps nan is a good option.

Sure, you can add me as a committer.

Best, Mark

**Comment by mren** [comment]
I created a [pull request](https://github.com/sutoiku/node-kafka/pull/3). Feel free to merge. :)

I will close this issue as the questions I had are resolved. Thanks for that!
